name: Stage-Appliction-Publishing

on:
  push:
    tags:
      - '*-dev'

jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.MY_REPO_PAT }}
        submodules: recursive
    - name: Fix git config
      run: |
        git submodule foreach 'git config --global url."https://x-access-token:${{ secrets.MY_REPO_PAT }}@github.com/cmtt-ru/heyka-sdk".insteadOf "https://github.com/cmtt-ru/heyka-sdk"'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: install dependencies
      run: npm install
    - name: set configuration
      run: cp ./electron-builder-stage.json ./electron-builder.json
    - name: create specific package.json file for test build
      run: cat package.json | sed 's/heyka/heyka-stage/' > tmp && mv tmp package.json
    - name: build for mac os
      run: npm run electron:build -- --mac --publish always
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CSC_LINK: ${{ secrets.apple_cert }}
        CSC_KEY_PASSWORD: ${{ secrets.apple_cert_password }}
        APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
        APPLE_ASP: ${{ secrets.APPLE_ASP }}
        CI: true

  build-linux-win:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.MY_REPO_PAT }}
        submodules: recursive
    - name: Fix git config
      run: |
        git submodule foreach 'git config --global url."https://x-access-token:${{ secrets.MY_REPO_PAT }}@github.com/cmtt-ru/heyka-sdk".insteadOf "https://github.com/cmtt-ru/heyka-sdk"'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: install wine
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32 && sudo apt-get install wine-stable
    - name: install dependencies
      run: npm install
    - name: set configuration
      run: cp ./electron-builder-stage.json ./electron-builder.json
    - name: create specific package.json file for test build
      run: cat package.json | sed 's/heyka/heyka-stage/' > tmp && mv tmp package.json
    - name: build for win and linux (without certificates)
      run: npm run electron:build -- --win --linux --publish always
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CI: true
